### ISSUE TITLE
[Sprint4] Implemention Plan

### ISSUE THREAD

**Issue by LeeHyunJong** [swsnu/swpp17-team3#10]
| Github ID            | Emoji |
| ---------------  | ------ |
| @pptnz               | 🌮 |
| @baryberri         | 🍩 | 
| @jim6829           |🍦 |
| @LeeHyunJong | 🍰 |
* Please choose your Emoji freely!

# Frontend
**ReplyService**🍩 
- makeNewReply(original_content: string, content: string) -> Promise<{status: boolean, reason: enum}>: Call backend api to make a new reply, and return the result.
- getReplyById(replyId: number) -> Promise: Call backend api to get specific reply by id.
- getReplyByUserId(userId: number) -> Promise<Reply[]>: Call backend api to get replies specified by user id.

**PhotoService**🌮
- uploadNewPhoto() -> Promise<{status: boolean, reason: enum, photoId: number}>: Call backend api to upload new photo, and return the result.
- ✅ getRandomPhoto() -> Promise: Call backend api to get a random photo link. 
- ✅ getPhotosByColor(color: number, photosCount: number) -> Promise<string[]>: Call backend api to get specific number of photo links, sorted by color.
- ✅ getPhoto(d: number) -> Promise: Call backend api to get specific photo by photo id.

**plane_list**🍩
- ngOnInit(): Depending on the current tab status(near or everywhere), get near planes and show them. Show only whose 'replied' attribute is false.
- onClickPlane(planeId: number): Open reply page with the given planeId. Decrement the today opening number limit by one.
- onClickEverywhereButton(): Change tab to everywhere. Call the getRandomPlane service function and show those planes. Show only whose 'replied' attribute is false.
- onClickNearMeButton(): Change tab to near me. Call the getNearPlane service function an show those planes. Show only whose 'replied' attribute is false.

**reply**🍩 
- ngOnInit(): Show the plane content using the given planeId.
- onClickCancelButton(): Redirect to plane_list page.
- onClickRefoldButton(content: string): Make a new Reply data. Set the plane's lifetime till tomorrow, and plane's 'replied' attribute to true.

**reply_detail**🍩
- ngOnInit(): Show reply contents by using given replyPlaneId.
- onClickCloseButton(): Redirect to inbox page.

**photo_list**🌮
- ✅ ngOnInit(): Using getRecentPhotos method, show preview of photos.
- ✅ goToDetail(photo: Photo): Show photo_detail page.
- onClickPostButton(): Show photo_post page.

**photo_post**🌮
- onClickCancelButton(): Redirect to photo_list page.
- onClickUploadButton() -> photo_id: Call System photo upload api. Make new photo database, and return the photo_id. Redirect to photo_post page with the uploaded photos preview shown.
- onClickPostButton(): Redirect to photo_list page. Decrement the writing limit by one.

**photo_detail**🌮
-  ✅ngOnInit(): Using the given PhotoId, show the photo.
-  ✅goBack(): Redirect to photo_list page.

**Auth Guard**🌮
- sign in한 user만 접근할 수 있는 url에 대해 frontend에서 접근을 막기.

**my page**🍩

**Comment by pptnz** [comment]
photo service, photo list, photo detail 구현하였습니다. 아직 구현하지 않은 부분은 다음과 같습니다.

**photo list**
- 상단 바 버튼: Planes, Write, Gallery, My page, Sign out
- Post 버튼: 아직 photo post를 구현하지 않아, 버튼도 구현하지 않았습니다.

**photo_detail**🌮
- 상단 바 버튼: Planes, Write, Gallery, My page, Sign out
- [tag 관련 이슈](https://github.com/swsnu/swpp17-team3/issues/15) 때문에 tag 내용을 화면에 띄우는 것을 아직 제대로 구현하지 못했습니다. 일단은 tag의 id(tag primary key)를 표시해두었습니다.
