### ISSUE TITLE
User service에서 getUser 기능 구현을 요청드립니다.

### ISSUE THREAD

**Issue by pptnz** [swsnu/swpp17-team3#14]
User service에서 id(user의 primary key)로 user model을 가져오는 getUser 기능이 필요합니다.
getUser의 용도는 다음과 같습니다.
- gallery나 plane list에서 user nickname 표시
- my page에서 user nickname 및 레벨, 오늘 남은 전송 수 등 표시

User.ts와 같이 user model을 만드는 것이 필요할 것으로 예상됩니다.

**Comment by baryberri** [comment]
이제 프론트엔드 `UserService`에서 `getUser()` 메소드가 작동합니다.
메소드는 `User` 클래스를 리턴합니다. `User` 클래스의 설명은 아래와 같습니다.

`user_id`: django user model의 id입니다. (저희의 custom User model의 id가 아닙니다.)
이는 request.user.id가 django user model의 id를 리턴하기 때문입니다. 만약 이를 통해 custom user model에 접근하고 싶으시면, plane과 마찬가지로 아래와 같은 코드를 사용해주세요.
```python
import django.contrib.auth.models as user_model
author = user_model.User.objects.get(id=request.user.id).user
```
`username`: 로그인한 user의 username입니다.
`today_write_count`, `today_reply_count`, `total_likes`: 백엔드와 같습니다.
