### ISSUE TITLE
현재 Tag 방식에 문제가 있어, 개선이 필요합니다.

### ISSUE THREAD

**Issue by pptnz** [swsnu/swpp17-team3#15]
현재 tag 방식에 문제가 있어, 개선이 필요합니다.
현재 tag는 plane 혹은 photo와 many to many 관계를 맺고 있습니다. many to many로 구현한 이유는 같은 tag를 가지는 plane 혹은 photo들을 묶기 위함입니다.
그런데 plane backend에서 plane을 생성할 때, tag를 계속해서 만들게 됩니다. 예를 들어, plane1이 work라는 tag를 가지고 있었다고 합시다. 그 다음에 plane2를 만들 때 work라는 tag를 달면, tag object가 또 생깁니다. 즉 work라는 tag object가 두 개가 됩니다. 이렇게 같은 내용의 tag가 따로 생성되면 원래 목적이었던 공통된 tag를 가지는 plane/photo를 묶는 게 불가능해집니다.

위의 문제에 대한 두 가지 개선 방안을 제안드립니다.
1. tag를 many to many가 아닌, string array field로 구현하는 것입니다. 저희 프로젝트에서 tag는 plane/photo에 대해 설명하는 역할을 할 뿐 tag를 통해 plane/photo를 검색하는 일이 없습니다. 이에 따라 tag를 string array field로 간단히 구현할 수 있습니다.

2. many to many 관계를 유지하고, 생성할 때 중복된 tag가 있는지 확인합니다.

어떻게 생각하시는지 또는 어느 방안이 좋을지 댓글 남겨주세요.

**Comment by jim6829** [comment]
음 생각해보니까 태그로 컨텐츠 검색하기 편리하게 하려고 many to many를 쓴 게 가장 큰데 검색 대신 컨텐츠를 리프레시하는 방향으로 바꿨기 때문에 굳이 별도 모델로 둘 필요가 없어보이네요. ArrayField 쓰는 거 저는 찬성입니다!

**Comment by pptnz** [comment]
의견 감사합니다! 다른 분들의 의견도 들어보고 결정하도록 하겠습니다.

**Comment by LeeHyunJong** [comment]
tag로 검색하는 기능이 없으니까 ArrayField가 낫겠네요!

**Comment by baryberri** [comment]
네 검색 기능이 없으면 당연히 string array가 나을 것 같아요!

**Comment by baryberri** [comment]
Write이 제 담당이니까 제가 수정하도록 하겠습니다!

**Comment by pptnz** [comment]
그러면 Plane과 Photo가 각각 string array field로 Tag를 가지는 것으로 정하겠습니다.
Plane의 Tag를 @baryberri가, Photo의 Tag를 제가 수정하겠습니다.

**Comment by baryberri** [comment]
CharField(max_length=10)으로 구현 완료했습니다.
